appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a8d1578b0700305bb1
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: Yx6KEes7vQYC7PiSoVMdMDurlAlzBqhaEi7f4I0VCW5flPxX2HgYKyp+ytwVrHXuAGYApAAk+KV6iw1fajg/6FxUNQ7oxmMOLpku1C2foaBT2k+hw6UWGQ9+LqieCNnUfj9jrkj7WXJ5Ug4wWkbm3hQ6+bSVDcQDXHhnuSTZkl0iowJRZs97nRNtZ7y7OeSAUA9sbXfWUZzJeJF1JQIv8d5NXeGI3D12p3e5ytDStHaDvDSUoNwqZzHqH3KKEVob/s/l9JFkYKHlqMQZOc07j/qdIfGZMLpdA+7vVeYAnlTyGga5q2nYZc/w2I1GXSorktyI2Z1iV9LOi/SpyYr8VLpO6S8D6juQoZaSq5vNXhyHaf7e6O0oTXWO264bnwTQfouMyReFtBJ0zYnUSZ/kL4fwClU4kiYK0cZJJArYFS6CQ+H8ZU0j5l1PgQ16fwx/nec6lzhT5zx8XzXfKoH0mr3zY5R9JheoDpWHsGzLbkMxUTNJ+wfLVt2zhGsCo6hBgB89kejmJfbuD6L7XZvVZfCtCtDSmbxMzN6aPUegYwnjV/Yh+MWzoQi6lhancGZS0jlyiWXqTm0PGSPZ0n9lITdSQj5IvrojOhJwwiJ8LQhEsF09NgHBEuv9CwVSncqPBAgPlWiEloZ3sWQYkKgqM/ZFP2vO706qdOMB7TTD1Q0=}
